apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGODB_URI: mongodb://mongodb+srv://elissianashaat83:gzIDL3u2Vc9gSRBS@cluster0.gjps4qp.mongodb.net/todolistDb?retryWrites=true&w=majority